version: 2.1
jobs:
  create-build-package:
    docker:
      - image: cimg/openjdk:17.0.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io/v2-jf | sh
      - run:
          name: Configure JFrog Creds
          command: |
            ./jf c add kim \
              --ARTIFACTORY_URL $ARTIFACTORY_URL \
              --user $ARTIFACTORY_USER \
              --password $ARTIFACTORY_APIKEY \
              --interactive=false
      - run:
          name: Maven Build
          command: |
            ./jf mvnc \
              --server-id-resolve kim \
              --server-id-deploy kim \
              --repo-resolve-releases libs-release \
              --repo-resolve-snapshots libs-snapshot \
              --repo-deploy-releases release-candidates \
              --repo-deploy-snapshots snapshots \
              --include-patterns "*.jar, *.pom, *.xml"

            ./jf mvn clean install

workflows:
  build:
    jobs:
      - create-build-package:
          context: artifactory
